### ISSUE TITLE
Occasional error on creating new world

### ISSUE THREAD

**Issue by PAndaContron** [Terasology/AdditionalWorlds#28]
Trying to generate a world with the "I'm getting thirsty" generator gives the following error:

`java.lang.RuntimeException: Cannot set a changed component with a null component variable`

At first I thought this was part of #27, but after tracing the code I found that the issue stems from trying to load the configuration for MountainsProvider. Why exactly this causes an issue is beyond me, since all of the code follows the [world generation tutorial](https://github.com/Terasology/TutorialWorldGeneration/wiki) very closely, and the MountainsProvider class in particular is identical to the one in that repository, yet the Tutorial World Generator runs perfectly fine.

Full stacktrace:

```Java
java.lang.RuntimeException: Cannot set a changed component with a null component variable
        at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
        at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:528)
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:704)
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:539)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:167)
        at org.terasology.engine.modes.loadProcesses.CreateWorldEntity.step(CreateWorldEntity.java:102)
        at org.terasology.engine.modes.StateLoading.update(StateLoading.java:243)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
        at org.terasology.engine.Terasology.main(Terasology.java:155)
```

**Comment by skaldarnar** [comment]
I don't know how to reproduce this, although it occured occasionally for me, too. I've renamed this issue to be more general, as I could also encounter this for Forest World and others…
Since many of the generators still use plugins this might also be a source of error.

**Comment by PAndaContron** [comment]
It's inconsistent for you? For me this occurs every time I try to load I'm Getting Thirsty. I haven't tried many of the newly merged generators though.

**Comment by PAndaContron** [comment]
I've found and fixed the issue in the latest commit. The issue was coming from the fact that there are multiple classes for certain configurations. Even though Java is fine with this since they are totally separate subclasses in completely separate places, it seems that the world generation code only loads configuration class names, so the 5 MountainsConfiguration classes and 2 CaveFacetProviderConfiguration classes in separate generators were causing issues. I think the reason why the issue was unreliable is because it would load only one of each configuration, and only the generator whose configuration was loaded would work.
